### PR TITLE
PR

### PR DESCRIPTION
**Pull request by fgsoftware1**
I removed unnecessary packages

### CODE REVIEW

**Comment by tetreum** [comment]
Ty for making this PR!
Got a question: Shouldn't `Packages/` folder be kept? It's `manifest.json` contains the list of applied packages to the project and i can't find it listed in the "recommended" `.gitignore` for Unity projects.(https://github.com/github/gitignore/blob/master/Unity.gitignore)

**Comment by fgsoftware1** [comment]
you want packages folder on repo?i can make this

**Comment by fgsoftware1** [comment]
hey man dont merge yet im making changes in menu and updating some script to latest version of unity

**Comment by fgsoftware1** [comment]
give me authorization to repo for publish a playable version

**Comment by fgsoftware1** [comment]
im trying make a model too

**Comment by fgsoftware1** [comment]
i update gitignore to ignore .idea folder and .dccache(file generated by vscode)

**Comment by fgsoftware1** [comment]
hey man where i can i talk with you?

**Comment by tetreum** [comment]
Do you have discord? RandomPlayer#0158

**Comment by fgsoftware1** [comment]
> Do you have discord? RandomPlayer#158

ok thanks

**Comment by fgsoftware1** [comment]
> Do you have discord? RandomPlayer#158

you wrote wrong should be 4 numbers not 3

**Comment by tetreum** [comment]
Github removed a 0 xD
```
RandomPlayer#0158
```

**Pull request merged**
